### ISSUE TITLE
回调函数执行多次

### ISSUE THREAD

**Issue by lakerszhy** [kagurazakayashi/EasylinkFlutter#1]
非常棒的插件的，正是需要的。
请教一个问题，使用示例代码配置成功后，如果马上再次开始配置，会再次收到回调消息。

**Comment by kagurazakayashi** [comment]
他们的 SDK 也包含不少问题，这个也是我暂时没解决的问题之一，抱歉不能帮到你。
看起来是上次配网时，手机端和设备端发出去的广播包，还在局域网里没有结束，还在广播，然后下次开始时，马上就监听到了。
如果你在之后解决了这个问题，欢迎 PR
